// /js/modules/config.js (結構與遺失函式修正版)

// 說明：
// 這個模組是應用程式的「設定手冊」。
// 它集中管理所有靜態的、不會在執行期間輕易改變的設定資料。

import { calculateArea } from "./utils.js";

// -------------------------------------------------------------------
// 基礎設定
// -------------------------------------------------------------------
const LOCAL_STORAGE_KEY = "dryerRecords";

// -------------------------------------------------------------------
// ▼▼▼ 所有設定檔都應定義在函式外部 ▼▼▼
// -------------------------------------------------------------------

// 1. HMI 區塊的背景圖檔名
const hmiLayouts = {
  vt8: {
    // ★ 修正：所有檔名前面都加上 "./img/" 路徑
    monitor1: "./img/vt8-hmi-monitor-1.svg",
    monitor2: "./img/vt8-hmi-monitor-2.svg",
    pid1: "./img/vt8-hmi-pid-1.svg",
    pid2: "./img/vt8-hmi-pid-2.svg",
  },
  vt7: {
    monitor1: "./img/vt7-hmi-monitor-1.svg",
    monitor2: "./img/vt7-hmi-monitor-2.svg",
    pid1: "./img/vt7-hmi-pid-1.svg",
  },
  vt6: {
    monitor1: "./img/vt6-hmi-monitor-1.svg",
    monitor2: "./img/vt6-hmi-monitor-2.svg",
    pid1: "./img/vt6-hmi-pid-1.svg",
  },
  vt5: {
    monitor1: "./img/vt5-hmi-monitor-1.svg",
    monitor2: "./img/vt5-hmi-monitor-2.svg",
    pid1: "./img/vt5-hmi-pid-1.svg",
  },
  vt1: {
    monitor1: "./img/vt1-hmi-monitor-1.svg",
    monitor2: "./img/vt1-hmi-monitor-2.svg",
    pid1: "./img/vt1-hmi-pid-1.svg",
  },
};
// ▼▼▼ 在此處新增 ▼▼▼
// 3. 各機型 Damper 佈局圖
const damperLayoutsByModel = {
  vt8: "./img/damper-layout-vt8.jpg",
  vt7: "./img/damper-layout-vt7.jpg",
  vt6: "./img/damper-layout-vt6.jpg",
  vt5: "./img/damper-layout-vt5.jpg",
  vt1: "./img/damper-layout-vt1.jpg",
};
// ▲▲▲ 新增結束 ▲▲▲

// 2. 各機型 HMI 區塊中的所有欄位
const hmiFieldsByModel = {
  vt8: {
    monitor1: [
      {
        id: "monitor_FT_C1",
        label: "1. FT C-1<small>(CCM)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_LEL_C1",
        label: "2. LEL C-1<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_FTA_1_2",
        label: "3. FTA-1-2<small>(CCM)</small>",
        position: { top: "10%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_XVA_1_2",
        label: "4. XVA-1-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_XV1_1_2",
        label: "5. XV1-1-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "25%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_PDT4_2",
        label: "6. PDT4-2<small>(mmAq)</small>",
        position: { top: "25%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_FTA_2_2",
        label: "7. FTA-2-2<small>(CCM)</small>",
        position: { top: "25%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_XVA_2_2",
        label: "8. XVA-2-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "25%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_PDT3_2",
        label: "9. PDT3-2<small>(mmAq)</small>",
        position: { top: "40%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_XV1_2_2",
        label: "10. XV1-2-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_PDT1_2",
        label: "11. PDT1-2<small>(mmAq)</small>",
        position: { top: "40%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_FT1_2",
        label: "12. FT1-2<small>(CCM)</small>",
        position: { top: "40%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "monitor_TE1_2",
        label: "13. TE1-2<small>(℃)</small>",
        position: { top: "55%", left: "10%", width: "15%", height: "10%" },
      },
    ],
    monitor2: [
      {
        id: "monitor_F4_4_relay",
        label: "14. F4-4中繼<small>(Hz)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "15%" },
      },
      {
        id: "monitor_PDT2_2",
        label: "15. PDT2-2<small>(mmAq)</small>",
        position: { top: "10%", left: "30%", width: "15%", height: "15%" },
      },
      {
        id: "monitor_XV2_2",
        label: "16. XV2-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "50%", width: "15%", height: "15%" },
      },
      {
        id: "monitor_LEL1_2",
        label: "17. LEL1-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "70%", width: "15%", height: "15%" },
      },
      {
        id: "monitor_TE7_2",
        label: "18. TE7-2<small>(℃)</small>",
        position: { top: "30%", left: "10%", width: "15%", height: "15%" },
      },
      {
        id: "monitor_F1_B_burn",
        label: "19. F1-B燃燒<small>(Hz)</small>",
        position: { top: "30%", left: "30%", width: "15%", height: "15%" },
      },
    ],
    pid1: [
      {
        id: "pid_F1_B_burn_SV",
        label: "20. F1-B燃燒/SV<small>(mmAq)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "20%" },
      },
      {
        id: "pid_F1_B_burn_Min",
        label: "21. F1-B燃燒/Min<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "30%", width: "15%", height: "20%" },
      },
      {
        id: "pid_F1_B_burn_Max",
        label: "22. F1-B燃燒/Max<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "50%", width: "15%", height: "20%" },
      },
      {
        id: "pid_F4_B_burn_SV",
        label: "23. F4-B燃燒/SV<small>(mmAq)</small>",
        position: { top: "40%", left: "10%", width: "15%", height: "20%" },
      },
      {
        id: "pid_F4_B_burn_Min",
        label: "24. F4-B燃燒/Min<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "30%", width: "15%", height: "20%" },
      },
      {
        id: "pid_F4_B_burn_Max",
        label: "25. F4-B燃燒/Max<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "50%", width: "15%", height: "20%" },
      },
    ],
    pid2: [
      {
        id: "pid_XV1_1_2_SV",
        label: "26. XV1-1-2/SV<small>(mmAq)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "20%" },
      },
      {
        id: "pid_XV1_1_2_Min",
        label: "27. XV1-1-2/Min<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "30%", width: "15%", height: "20%" },
      },
      {
        id: "pid_XV1_1_2_Max",
        label: "28. XV1-1-2/Max<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "50%", width: "15%", height: "20%" },
      },
      {
        id: "pid_XV1_2_2_SV",
        label: "29. XV1-2-2/SV<small>(mmAq)</small>",
        position: { top: "40%", left: "10%", width: "15%", height: "20%" },
      },
      {
        id: "pid_XV1_2_2_Min",
        label: "30. XV1-2-2/Min<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "30%", width: "15%", height: "20%" },
      },
      {
        id: "pid_XV1_2_2_Max",
        label: "31. XV1-2-2/Max<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "50%", width: "15%", height: "20%" },
      },
    ],
  },
  vt7: {
    monitor1: [
      {
        id: "vt7_monitor_1",
        label: "1. FT 1-2<small>(CCM)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_2",
        label: "2. XVB-2<small>(mm/s)</small>",
        position: { top: "10%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_3",
        label: "3. FB-2桶槽<small>(Hz)</small>",
        position: { top: "10%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_4",
        label: "4. FTA-2-1<small>(CMM)</small>",
        position: { top: "10%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_5",
        label: "5. XVA-2-1<small>(%)</small>",
        validation: "percentage",
        position: { top: "25%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_6",
        label: "6. XV1-2-1<small>(%)</small>",
        validation: "percentage",
        position: { top: "25%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_7",
        label: "7. PDT3-3<small>(mmAq)</small>",
        position: { top: "25%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_8",
        label: "8. FTA-2-2<small>(CMM)</small>",
        position: { top: "25%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_9",
        label: "9. XVA-2-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_10",
        label: "10. PDT3-4<small>(mmAq)</small>",
        position: { top: "40%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_11",
        label: "11. XV1-2-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_12",
        label: "12. TE1-2<small>(℃)</small>",
        position: { top: "40%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "vt7_monitor_13",
        label: "13. FT1-2<small>(CMM)</small>",
        position: { top: "55%", left: "10%", width: "15%", height: "10%" },
      },
    ],
    monitor2: [
      {
        id: "vt7_monitor_14",
        label: "14. LEL1-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "10%", width: "15%", height: "15%" },
      },
      {
        id: "vt7_monitor_15",
        label: "15. PDT2-2<small>(mmAq)</small>",
        position: { top: "10%", left: "30%", width: "15%", height: "15%" },
      },
      {
        id: "vt7_monitor_16",
        label: "16. XV2-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "50%", width: "15%", height: "15%" },
      },
      {
        id: "vt7_monitor_17",
        label: "17. F1-B燃燒<small>(mm/s)</small>",
        position: { top: "10%", left: "70%", width: "15%", height: "15%" },
      },
      {
        id: "vt7_monitor_18",
        label: "18. F1-B燃燒<small>(Hz)</small>",
        position: { top: "30%", left: "10%", width: "15%", height: "15%" },
      },
      {
        id: "vt7_monitor_19",
        label: "19. TE7-2<small>(℃)</small>",
        position: { top: "30%", left: "30%", width: "15%", height: "15%" },
      },
    ],
    pid1: [
      {
        id: "vt7_pid_20",
        label: "20. XV1-2-1/SV<small>(mmAq)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "20%" },
      },
      {
        id: "vt7_pid_21",
        label: "21. XV1-2-1/Min<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "30%", width: "15%", height: "20%" },
      },
      {
        id: "vt7_pid_22",
        label: "22. XV1-2-1/Max<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "50%", width: "15%", height: "20%" },
      },
      {
        id: "vt7_pid_23",
        label: "23. XV1-2-2/SV<small>(mmAq)</small>",
        position: { top: "40%", left: "10%", width: "15%", height: "20%" },
      },
      {
        id: "vt7_pid_24",
        label: "24. XV1-2-2/Min<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "30%", width: "15%", height: "20%" },
      },
      {
        id: "vt7_pid_25",
        label: "25. XV1-2-2/Max<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "50%", width: "15%", height: "20%" },
      },
    ],
  },
  vt6: {
    monitor1: [
      {
        id: "vt6_monitor_1",
        label: "1. FT 1-2<small>(CMM)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_2",
        label: "2. XVA-1-1<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_3",
        label: "3. PDT3-1<small>(mmAq)</small>",
        position: { top: "10%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_4",
        label: "4. XV1-1-1<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_5",
        label: "5. FTA-2-1<small>(CMM)</small>",
        position: { top: "25%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_6",
        label: "6. XVA-1-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "25%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_7",
        label: "7. PDT3-2<small>(mmAq)</small>",
        position: { top: "25%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_8",
        label: "8. XV1-1-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "25%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_9",
        label: "9. TE1-2<small>(℃)</small>",
        position: { top: "40%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt6_monitor_10",
        label: "10. FT1-1<small>(CMM)</small>",
        position: { top: "40%", left: "30%", width: "15%", height: "10%" },
      },
    ],
    monitor2: [
      {
        id: "vt6_monitor_11",
        label: "11. LEL1-1<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "10%", width: "15%", height: "15%" },
      },
      {
        id: "vt6_monitor_12",
        label: "12. PDT2-1<small>(mmAq)</small>",
        position: { top: "10%", left: "30%", width: "15%", height: "15%" },
      },
      {
        id: "vt6_monitor_13",
        label: "13. XV2-1<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "50%", width: "15%", height: "15%" },
      },
      {
        id: "vt6_monitor_14",
        label: "14. F1-A燃燒<small>(mm/s)</small>",
        position: { top: "10%", left: "70%", width: "15%", height: "15%" },
      },
      {
        id: "vt6_monitor_15",
        label: "15. F1-A燃燒<small>(Hz)</small>",
        position: { top: "30%", left: "10%", width: "15%", height: "15%" },
      },
      {
        id: "vt6_monitor_16",
        label: "16. TE7-1<small>(℃)</small>",
        position: { top: "30%", left: "30%", width: "15%", height: "15%" },
      },
    ],
    pid1: [
      {
        id: "vt6_pid_17",
        label: "17. XV1-1-1/SV<small>(mmAq)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "20%" },
      },
      {
        id: "vt6_pid_18",
        label: "18. XV1-1-1/Min<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "30%", width: "15%", height: "20%" },
      },
      {
        id: "vt6_pid_19",
        label: "19. XV1-1-1/Max<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "50%", width: "15%", height: "20%" },
      },
      {
        id: "vt6_pid_20",
        label: "20. XV1-1-2/SV<small>(mmAq)</small>",
        position: { top: "40%", left: "10%", width: "15%", height: "20%" },
      },
      {
        id: "vt6_pid_21",
        label: "21. XV1-1-2/Min<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "30%", width: "15%", height: "20%" },
      },
      {
        id: "vt6_pid_22",
        label: "22. XV1-1-2/Max<small>(%)</small>",
        validation: "percentage",
        position: { top: "40%", left: "50%", width: "15%", height: "20%" },
      },
    ],
  },
  vt5: {
    monitor1: [
      {
        id: "vt5_monitor_1",
        label: "1. FTA-1-2<small>(CMM)</small>",
        position: { top: "10%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_2",
        label: "2. XVA-1-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_3",
        label: "3. XV1-1-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "10%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_4",
        label: "4. PDT1-2<small>(mmAq)</small>",
        position: { top: "10%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_5",
        label: "5. FTA-2-2<small>(CMM)</small>",
        position: { top: "25%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_6",
        label: "6. XVA-2-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "25%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_7",
        label: "7. PDT3-2<small>(mmAq)</small>",
        position: { top: "25%", left: "50%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_8",
        label: "8. XV1-2-2<small>(%)</small>",
        validation: "percentage",
        position: { top: "25%", left: "70%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_9",
        label: "9. FT1-2<small>(CMM)</small>",
        position: { top: "40%", left: "10%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_10",
        label: "10. TE1-2<small>(℃)</small>",
        position: { top: "40%", left: "30%", width: "15%", height: "10%" },
      },
      {
        id: "vt5_monitor_11",
        label: "11. F-4-2中繼<small>(Hz)</small>",
        position: { top: "40%", left: "50%", width: "15%", height: "10%" },
      },
    ],
    monitor2: [], // VT5 沒有 monitor2
    pid1: [], // VT5 沒有 pid1
  },
  vt1: {
    // VT1 待確認，暫時留空
    monitor1: [],
    monitor2: [],
    pid1: [],
  },
};

// -------------------------------------------------------------------
// 風量量測設定 (所有機型)
// -------------------------------------------------------------------
const allDryerAirVolumeMeasurements = {
  vt8: [
    {
      id: "chamber1_supply",
      label: "1室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-supply.jpg",
      order: 100,
    },
    {
      id: "chamber2_supply_after_filter",
      label: "2室給氣(濾網後)",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-supply-after-filter.jpg",
      order: 101,
    },
    {
      id: "chamber2_supply_before_filter",
      label: "2室給氣(濾網前)",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-supply-before-filter.jpg",
      order: 102,
    },
    {
      id: "chamber1_exhaust_before_motor",
      label: "1室排氣(馬達前)",
      duct: "0.65*0.65",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-exhaust-before-motor.jpg",
      order: 103,
    },
    {
      id: "chamber2_exhaust_before_motor",
      label: "2室排氣(馬達前)",
      duct: "0.45*0.45",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-exhaust-before-motor.jpg",
      order: 104,
    },
    {
      id: "chamber1_upper_ac_supply",
      label: "1室上部AC給氣",
      duct: "Ф0.255",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-upper-ac-supply.jpg",
      order: 105,
    },
    {
      id: "chamber1_upper_ac_supply_front",
      label: "1室上部AC給氣-前",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-upper-ac-supply-front.jpg",
      order: 106,
    },
    {
      id: "chamber1_upper_ac_supply_rear",
      label: "1室上部AC給氣-後",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt8-chamber1-upper-ac-supply-rear.jpg",
      order: 107,
    },
    {
      id: "chamber2_upper_ac_supply",
      label: "2室上部AC給氣",
      duct: "Ф0.255",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-upper-ac-supply.jpg",
      order: 108,
    },
    {
      id: "chamber2_upper_ac_supply_front",
      label: "2室上部AC給氣-前",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-upper-ac-supply-front.jpg",
      order: 109,
    },
    {
      id: "chamber2_upper_ac_supply_rear",
      label: "2室上部AC給氣-後",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt8-chamber2-upper-ac-supply-rear.jpg",
      order: 110,
    },
    {
      id: "upper_ac_top_exhaust_outdoor",
      label: "上部AC+TOP排氣(屋外)",
      duct: "φ0.30",
      status: "normal",
      imageUrl: "./img/vt8-upper-ac-top-exhaust-outdoor.jpg",
      order: 111,
    },
    {
      id: "lower_ac_exhaust",
      label: "下部AC排氣",
      duct: "0.35*0.35",
      status: "normal",
      imageUrl: "./img/vt8-lower-ac-exhaust.jpg",
      order: 112,
    },
    {
      id: "lower_ac_exhaust_outdoor",
      label: "下部AC排氣(屋外)",
      duct: "φ0.30",
      status: "normal",
      imageUrl: "./img/vt8-lower-ac-exhaust-outdoor.jpg",
      order: 113,
    },
  ],
  vt7: [
    {
      id: "chamber1_supply_vt7",
      label: "1室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-supply.jpg",
      order: 100,
    },
    {
      id: "chamber1_exhaust_vt7",
      label: "1室排氣",
      duct: "0.75*0.5",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-exhaust.jpg",
      order: 101,
    },
    {
      id: "chamber2_supply_vt7",
      label: "2室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt7-chamber2-supply.jpg",
      order: 102,
    },
    {
      id: "chamber2_exhaust_vt7",
      label: "2室排氣",
      duct: "0.75*0.5",
      status: "normal",
      imageUrl: "./img/vt7-chamber2-exhaust.jpg",
      order: 103,
    },
    {
      id: "chamber1_2_exhaust_vt7",
      label: "1、2室排氣",
      duct: "0.64*0.67",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-2-exhaust.jpg",
      order: 104,
    },
    {
      id: "chamber1_upper_ac_supply_upper_vt7",
      label: "１室上部AC給氣(上)",
      duct: "φ0.40",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-upper-ac-supply-upper.jpg",
      order: 105,
    },
    {
      id: "chamber1_upper_ac_supply_lower_vt7",
      label: "１室上部AC給氣(下)",
      duct: "φ0.40",
      status: "normal",
      imageUrl: "./img/vt7-chamber1-upper-ac-supply-lower.jpg",
      order: 106,
    },
    {
      id: "chamber1_upper_ac_exhaust_vt7",
      label: "１室上部AC排氣",
      duct: "沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 107,
    },
    {
      id: "chamber2_upper_ac_supply_vt7",
      label: "２室上部AC給氣",
      duct: "φ0.255",
      status: "normal",
      imageUrl: "./img/vt7-chamber2-upper-ac-supply.jpg",
      order: 108,
    },
    {
      id: "chamber2_upper_ac_exhaust_vt7",
      label: "２室上部AC排氣",
      duct: "沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 109,
    },
    {
      id: "top_exhaust_vt7",
      label: "TOP排氣",
      duct: "0.5*0.5",
      status: "normal",
      imageUrl: "./img/vt7-top-exhaust.jpg",
      order: 110,
    },
    {
      id: "upper_ac_exhaust_outdoor_vt7",
      label: "上部AC排氣(戶外)",
      duct: "φ0.35",
      status: "normal",
      imageUrl: "./img/vt7-upper-ac-exhaust-outdoor.jpg",
      order: 111,
    },
    {
      id: "lower_ac_supply_vt7",
      label: "下部AC給氣",
      duct: "φ0.30",
      status: "normal",
      imageUrl: "./img/vt7-lower-ac-supply.jpg",
      order: 112,
    },
    {
      id: "chamber2_lower_ac_exhaust_vt7",
      label: "2室下部AC排氣",
      duct: "0.5*0.37",
      status: "normal",
      imageUrl: "./img/vt7-chamber2-lower-ac-exhaust.jpg",
      order: 113,
    },
  ],
  vt6: [
    {
      id: "chamber1_supply_vt6",
      label: "1室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-supply.jpg",
      order: 100,
    },
    {
      id: "chamber1_exhaust_vt6",
      label: "1室排氣",
      duct: "0.85*0.58",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-exhaust.jpg",
      order: 101,
    },
    {
      id: "chamber2_supply_vt6",
      label: "2室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt6-chamber2-supply.jpg",
      order: 102,
    },
    {
      id: "chamber2_exhaust_vt6",
      label: "2室排氣",
      duct: "0.85*0.28",
      status: "normal",
      imageUrl: "./img/vt6-chamber2-exhaust.jpg",
      order: 103,
    },
    {
      id: "chamber1_upper_ac_supply_upper_vt6",
      label: "１室上部AC給氣(上)",
      duct: "φ0.4",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-upper-ac-supply-upper.jpg",
      order: 104,
    },
    {
      id: "chamber1_upper_ac_supply_lower_vt6",
      label: "１室上部AC給氣(下)",
      duct: "φ0.4",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-upper-ac-supply-lower.jpg",
      order: 105,
    },
    {
      id: "chamber1_upper_ac_exhaust_vt6",
      label: "１室上部AC排氣",
      duct: "0.6*0.35",
      status: "normal",
      imageUrl: "./img/vt6-chamber1-upper-ac-exhaust.jpg",
      order: 106,
    },
    {
      id: "chamber2_upper_ac_supply_vt6",
      label: "２室上部AC給氣",
      duct: "φ0.25",
      status: "normal",
      imageUrl: "./img/vt6-chamber2-upper-ac-supply.jpg",
      order: 107,
    },
    {
      id: "chamber2_upper_ac_exhaust_vt6",
      label: "２室上部AC排氣",
      duct: "0.6*0.35",
      status: "normal",
      imageUrl: "./img/vt6-chamber2-upper-ac-exhaust.jpg",
      order: 108,
    },
    {
      id: "upper_ac_exhaust_1_2_vt6",
      label: "上部AC排氣(1、2室)",
      duct: "0.30*0.30",
      status: "normal",
      imageUrl: "./img/vt6-upper-ac-exhaust-1-2.jpg",
      order: 109,
    },
    {
      id: "top_exhaust_right_vt6",
      label: "TOP排氣-右",
      duct: "0.35*0.18",
      status: "normal",
      imageUrl: "./img/vt6-top-exhaust-right.jpg",
      order: 110,
    },
    {
      id: "top_exhaust_left_vt6",
      label: "TOP排氣-左",
      duct: "0.35*0.18",
      status: "normal",
      imageUrl: "./img/vt6-top-exhaust-left.jpg",
      order: 111,
    },
    {
      id: "lower_ac_supply_vt6",
      label: "下部AC給氣",
      duct: "測定危険",
      status: "dangerous",
      imageUrl: "",
      order: 112,
    },
    {
      id: "lower_ac_exhaust_vt6",
      label: "下部AC排氣",
      duct: "0.3*0.42",
      status: "normal",
      imageUrl: "./img/vt6-lower-ac-exhaust.jpg",
      order: 113,
    },
  ],
  vt1: [
    {
      id: "chamber1_supply_motor_before_vt1",
      label: "１室給氣(馬達前)",
      duct: "0.45*0.45",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-supply-motor-before.jpg",
      order: 100,
    },
    {
      id: "chamber1_supply_motor_after_vt1",
      label: "１室給氣(馬達後)",
      duct: "0.8*0.3",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-supply-motor-after.jpg",
      order: 101,
    },
    {
      id: "chamber1_exhaust_motor_before_vt1",
      label: "１室排氣(馬達前)",
      duct: "0.55*0.63",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-exhaust-motor-before.jpg",
      order: 102,
    },
    {
      id: "chamber1_exhaust_motor_after_vt1",
      label: "１室排氣(馬達後)",
      duct: "0.65*0.42",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-exhaust-motor-after.jpg",
      order: 103,
    },
    {
      id: "chamber2_supply_motor_before_vt1",
      label: "２室給氣(馬達前)",
      duct: "0.35*0.35",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-supply-motor-before.jpg",
      order: 104,
    },
    {
      id: "chamber2_supply_motor_after_vt1",
      label: "２室給氣(馬達後)",
      duct: "0.8*0.3",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-supply-motor-after.jpg",
      order: 105,
    },
    {
      id: "chamber2_exhaust_motor_before_vt1",
      label: "２室排氣(馬達前)",
      duct: "0.45*0.45",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-exhaust-motor-before.jpg",
      order: 106,
    },
    {
      id: "chamber2_exhaust_motor_after_vt1",
      label: "２室排氣(馬達後)",
      duct: "0.60*0.33",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-exhaust-motor-after.jpg",
      order: 107,
    },
    {
      id: "chamber1_upper_ac_supply_vt1",
      label: "1室上部AC給氣",
      duct: "0.45*0.45",
      status: "normal",
      imageUrl: "./img/vt1-chamber1-upper-ac-supply.jpg",
      order: 108,
    },
    {
      id: "upper_ac_supply_vt1",
      label: "上部AC給氣",
      duct: "0.39*0.65",
      status: "normal",
      imageUrl: "./img/vt1-upper-ac-supply.jpg",
      order: 109,
    },
    {
      id: "chamber2_upper_ac_supply_vt1",
      label: "2室上部AC給氣",
      duct: "0.3*0.3",
      status: "normal",
      imageUrl: "./img/vt1-chamber2-upper-ac-supply.jpg",
      order: 110,
    },
    {
      id: "top_roll_exhaust_fan_before_vt1",
      label: "TOP ROLL排氣室(風扇前)",
      duct: "0.5*0.22",
      status: "normal",
      imageUrl: "./img/vt1-top-roll-exhaust-fan-before.jpg",
      order: 111,
    },
    {
      id: "top_roll_exhaust_fan_after_vt1",
      label: "TOP ROLL排氣室(風扇後)",
      duct: "0.7*0.45",
      status: "normal",
      imageUrl: "./img/vt1-top-roll-exhaust-fan-after.jpg",
      order: 112,
    },
    {
      id: "lower_ac_supply_vt1",
      label: "下部AC給氣",
      duct: "0.39*0.39",
      status: "normal",
      imageUrl: "./img/vt1-lower-ac-supply.jpg",
      order: 113,
    },
    {
      id: "lower_ac_exhaust_vt1",
      label: "下部AC排氣",
      duct: "0.38*0.34",
      status: "normal",
      imageUrl: "./img/vt1-lower-ac-exhaust.jpg",
      order: 114,
    },
  ],
  vt5: [
    {
      id: "chamber1_supply_vt5",
      label: "１室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-supply.jpg",
      order: 100,
    },
    {
      id: "chamber1_exhaust_vt5",
      label: "１室排氣",
      duct: "0.43*0.58",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-exhaust.jpg",
      order: 101,
    },
    {
      id: "chamber2_supply_vt5",
      label: "２室給氣",
      duct: "φ0.55",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-supply.jpg",
      order: 102,
    },
    {
      id: "chamber2_exhaust_vt5",
      label: "２室 排氣",
      duct: "0.35*0.37",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-exhaust.jpg",
      order: 103,
    },
    {
      id: "chamber1_2_exhaust_vt5",
      label: "1、2室排氣",
      duct: "0.6*0.6",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-2-exhaust.jpg",
      order: 104,
    },
    {
      id: "chamber1_upper_ac_supply_vt5",
      label: "１室上部AC給氣",
      duct: "φ0.24",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-upper-ac-supply.jpg",
      order: 105,
    },
    {
      id: "chamber1_upper_ac_supply_front_vt5",
      label: "１室上部AC給氣-前",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-upper-ac-supply-front.jpg",
      order: 106,
    },
    {
      id: "chamber1_upper_ac_supply_rear_vt5",
      label: "１室上部AC給氣-後",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt5-chamber1-upper-ac-supply-rear.jpg",
      order: 107,
    },
    {
      id: "chamber2_upper_ac_supply_vt5",
      label: "２室上部AC給氣",
      duct: "φ0.24",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-upper-ac-supply.jpg",
      order: 108,
    },
    {
      id: "chamber2_upper_ac_supply_front_vt5",
      label: "２室上部AC給氣-前",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-upper-ac-supply-front.jpg",
      order: 109,
    },
    {
      id: "chamber2_upper_ac_supply_rear_vt5",
      label: "２室上部AC給氣-後",
      duct: "φ0.15",
      status: "normal",
      imageUrl: "./img/vt5-chamber2-upper-ac-supply-rear.jpg",
      order: 110,
    },
    {
      id: "upper_ac_exhaust_vt5",
      label: "上部AC排氣",
      duct: "0.40*0.40 沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 111,
    },
    {
      id: "lower_ac_supply_vt5",
      label: "下部AC給氣",
      duct: "0.39*0.39 沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 112,
    },
    {
      id: "lower_ac_exhaust_vt5",
      label: "下部AC排氣",
      duct: "0.35*0.35 沒量測點",
      status: "unavailable",
      imageUrl: "",
      order: 113,
    },
  ],
};

const getAirVolumeMeasurementsByModel = (model) => {
  const measurements = allDryerAirVolumeMeasurements[model] || [];
  // 由於物件是引用類型，為了避免修改原始定義，這裡複製一份
  const clonedMeasurements = JSON.parse(JSON.stringify(measurements));

  clonedMeasurements.forEach((m) => {
    // 只有在 status 為 'normal' 時才計算面積，否則面積設為0
    if (m.status === "normal") {
      m.area = calculateArea(m.duct);
    } else {
      m.area = 0;
    }
    // 確保 imageUrl 屬性存在，即使為 undefined 也要有，以便 UI 判斷
    if (!m.imageUrl) {
      m.imageUrl = "";
    }
  });
  return clonedMeasurements;
};

// -------------------------------------------------------------------
// 技術溫測點設定
// -------------------------------------------------------------------
const techTempPoints = [
  ...Array.from({ length: 11 }, (_, i) => ({
    id: `${i + 1}`,
    label: `技術溫測實溫_${i + 1}`,
    orderOffset: 200 + i * 10,
  })),
  { id: "T1", label: "技術溫測實溫_T1", orderOffset: 200 + 11 * 10 },
  { id: "T2", label: "技術溫測實溫_T2", orderOffset: 200 + 12 * 10 },
  ...Array.from({ length: 11 }, (_, i) => ({
    id: `${i + 12}`,
    label: `技術溫測實溫_${i + 12}`,
    orderOffset: 200 + (13 + i) * 10,
  })),
];

// -------------------------------------------------------------------
// 給排氣 DAMPER 設定 (所有機型)
// -------------------------------------------------------------------

// 輔助函式：建立一個包含通用屬性的 Damper 欄位設定陣列
const createDamperConfig = (fields) => {
  return fields.map((field) => ({
    ...field,
    recordTypes: ["conditionSetting"],
    group: "damperOpening",
    elemType: "number",
    inTable: true,
    // ★★★ 修正點 1: 使用更穩健的正規表示式，確保能正確移除標籤結尾的單位，例如 (%) 或 (℃)
    csvHeader: `給排氣damper開度_${field.label.replace(/\s*\([^)]*\)$/, "")}`,
    validation: "percentage",
  }));
};

const allDamperOpeningFields = {
  vt8: createDamperConfig([
    {
      id: "damper_vt8_01",
      dataKey: "damperOpeningData.vt8_01",
      label: "① TOP排氣扇(FAN) (%)",
      order: 601,
    },
    {
      id: "damper_vt8_02",
      dataKey: "damperOpeningData.vt8_02",
      label: "② TOP室排氣(右) (%)",
      order: 602,
    },
    {
      id: "damper_vt8_03",
      dataKey: "damperOpeningData.vt8_03",
      label: "③ TOP室排氣(左) (%)",
      order: 603,
    },
    {
      id: "damper_vt8_04",
      dataKey: "damperOpeningData.vt8_04",
      label: "④ 上部AC給氣(主) (%)",
      order: 604,
    },
    {
      id: "damper_vt8_05",
      dataKey: "damperOpeningData.vt8_05",
      label: "⑤ 1室上AC給氣(C) (%)",
      order: 605,
    },
    {
      id: "damper_vt8_06",
      dataKey: "damperOpeningData.vt8_06",
      label: "⑥ 1室上AC給氣(右) (%)",
      order: 606,
    },
    {
      id: "damper_vt8_07",
      dataKey: "damperOpeningData.vt8_07",
      label: "⑦ 1室上AC給氣(左) (%)",
      order: 607,
    },
    {
      id: "damper_vt8_08",
      dataKey: "damperOpeningData.vt8_08",
      label: "⑧ 1室上AC排氣(A) (%)",
      order: 608,
    },
    {
      id: "damper_vt8_09",
      dataKey: "damperOpeningData.vt8_09",
      label: "⑨ 1室上AC排氣(右) (%)",
      order: 609,
    },
    {
      id: "damper_vt8_10",
      dataKey: "damperOpeningData.vt8_10",
      label: "⑩ 1室上AC排氣(左) (%)",
      order: 610,
    },
    {
      id: "damper_vt8_11",
      dataKey: "damperOpeningData.vt8_11",
      label: "⑪ 1室排氣(右) (%)",
      order: 611,
    },
    {
      id: "damper_vt8_12",
      dataKey: "damperOpeningData.vt8_12",
      label: "⑫ 1室排氣(左) (%)",
      order: 612,
    },
    {
      id: "damper_vt8_13",
      dataKey: "damperOpeningData.vt8_13",
      label: "⑬ 2室上AC給氣(D) (%)",
      order: 613,
    },
    {
      id: "damper_vt8_14",
      dataKey: "damperOpeningData.vt8_14",
      label: "⑭ 2室上AC給氣(右) (%)",
      order: 614,
    },
    {
      id: "damper_vt8_15",
      dataKey: "damperOpeningData.vt8_15",
      label: "⑮ 2室上AC給氣(左) (%)",
      order: 615,
    },
    {
      id: "damper_vt8_16",
      dataKey: "damperOpeningData.vt8_16",
      label: "⑯ 2室上AC排氣(B) (%)",
      order: 616,
    },
    {
      id: "damper_vt8_17",
      dataKey: "damperOpeningData.vt8_17",
      label: "⑰ 2室上AC排氣(右) (%)",
      order: 617,
    },
    {
      id: "damper_vt8_18",
      dataKey: "damperOpeningData.vt8_18",
      label: "⑱ 2室上AC排氣(左) (%)",
      order: 618,
    },
    {
      id: "damper_vt8_19",
      dataKey: "damperOpeningData.vt8_19",
      label: "⑲ 2室排氣(右) (%)",
      order: 619,
    },
    {
      id: "damper_vt8_20",
      dataKey: "damperOpeningData.vt8_20",
      label: "⑳ 2室排氣(左) (%)",
      order: 620,
    },
    {
      id: "damper_vt8_21",
      dataKey: "damperOpeningData.vt8_21",
      label: "㉑ 1室外部新鮮空氣 (%)",
      order: 621,
    },
    {
      id: "damper_vt8_22",
      dataKey: "damperOpeningData.vt8_22",
      label: "㉒ 2室外部新鮮空氣 (%)",
      order: 622,
    },
    {
      id: "damper_vt8_23",
      dataKey: "damperOpeningData.vt8_23",
      label: "㉓ 下部AC給氣(主) (%)",
      order: 623,
    },
    {
      id: "damper_vt8_24",
      dataKey: "damperOpeningData.vt8_24",
      label: "㉔ 下部AC排氣FAN (%)",
      order: 624,
    },
    {
      id: "damper_vt8_25",
      dataKey: "damperOpeningData.vt8_25",
      label: "㉕ 1室給氣(右) (%)",
      order: 625,
    },
    {
      id: "damper_vt8_26",
      dataKey: "damperOpeningData.vt8_26",
      label: "㉖ 1室給氣(左) (%)",
      order: 626,
    },
    {
      id: "damper_vt8_27",
      dataKey: "damperOpeningData.vt8_27",
      label: "㉗ 1下部AC排氣(右) (%)",
      order: 627,
    },
    {
      id: "damper_vt8_28",
      dataKey: "damperOpeningData.vt8_28",
      label: "㉘ 1下部AC排氣(左) (%)",
      order: 628,
    },
    {
      id: "damper_vt8_29",
      dataKey: "damperOpeningData.vt8_29",
      label: "㉙ 1下部AC給氣(右) (%)",
      order: 629,
    },
    {
      id: "damper_vt8_30",
      dataKey: "damperOpeningData.vt8_30",
      label: "㉚ 1下部AC給氣(左) (%)",
      order: 630,
    },
    {
      id: "damper_vt8_31",
      dataKey: "damperOpeningData.vt8_31",
      label: "㉛ 2室給氣(右) (%)",
      order: 631,
    },
    {
      id: "damper_vt8_32",
      dataKey: "damperOpeningData.vt8_32",
      label: "㉜ 2室給氣(左) (%)",
      order: 632,
    },
    {
      id: "damper_vt8_33",
      dataKey: "damperOpeningData.vt8_33",
      label: "㉝ 2下部AC排氣(右) (%)",
      order: 633,
    },
    {
      id: "damper_vt8_34",
      dataKey: "damperOpeningData.vt8_34",
      label: "㉞ 2下部AC排氣(左) (%)",
      order: 634,
    },
    {
      id: "damper_vt8_35",
      dataKey: "damperOpeningData.vt8_35",
      label: "㉟ 2下部AC給氣(右) (%)",
      order: 635,
    },
    {
      id: "damper_vt8_36",
      dataKey: "damperOpeningData.vt8_36",
      label: "㊱ 2下部AC給氣(左) (%)",
      order: 636,
    },
    {
      id: "damper_vt8_37",
      dataKey: "damperOpeningData.vt8_37",
      label: "㊲ 1室下AC給氣(副) (%)",
      order: 637,
    },
    {
      id: "damper_vt8_38",
      dataKey: "damperOpeningData.vt8_38",
      label: "㊳ 2室下AC給氣(副) (%)",
      order: 638,
    },
  ]),

  vt7: createDamperConfig([
    {
      id: "damper_vt7_01",
      dataKey: "damperOpeningData.vt7_01",
      label: "① TOP排氣扇(FAN) (%)",
      order: 701,
    },
    {
      id: "damper_vt7_02",
      dataKey: "damperOpeningData.vt7_02",
      label: "② TOP室排氣(右) (%)",
      order: 702,
    },
    {
      id: "damper_vt7_03",
      dataKey: "damperOpeningData.vt7_03",
      label: "③ TOP室排氣(左) (%)",
      order: 703,
    },
    {
      id: "damper_vt7_04",
      dataKey: "damperOpeningData.vt7_04",
      label: "④ 1室上AC給氣(上) (%)",
      order: 704,
    },
    {
      id: "damper_vt7_05",
      dataKey: "damperOpeningData.vt7_05",
      label: "⑤ 1室上AC給氣(下) (%)",
      order: 705,
    },
    {
      id: "damper_vt7_06",
      dataKey: "damperOpeningData.vt7_06",
      label: "⑥ 1室上AC排氣(右) (%)",
      order: 706,
    },
    {
      id: "damper_vt7_07",
      dataKey: "damperOpeningData.vt7_07",
      label: "⑦ 1室上AC排氣(左) (%)",
      order: 707,
    },
    {
      id: "damper_vt7_08",
      dataKey: "damperOpeningData.vt7_08",
      label: "⑧ 1室給氣(右) (%)",
      order: 708,
    },
    {
      id: "damper_vt7_09",
      dataKey: "damperOpeningData.vt7_09",
      label: "⑨ 1室給氣(左) (%)",
      order: 709,
    },
    {
      id: "damper_vt7_10",
      dataKey: "damperOpeningData.vt7_10",
      label: "⑩ 2室上AC給氣 (%)",
      order: 710,
    },
    {
      id: "damper_vt7_11",
      dataKey: "damperOpeningData.vt7_11",
      label: "⑪ 2室上AC排氣(左) (%)",
      order: 711,
    },
    {
      id: "damper_vt7_12",
      dataKey: "damperOpeningData.vt7_12",
      label: "⑫ 2室上AC排氣(右) (%)",
      order: 712,
    },
    {
      id: "damper_vt7_14",
      dataKey: "damperOpeningData.vt7_14",
      label: "⑭ 2室給氣(右) (%)",
      order: 714,
    },
    {
      id: "damper_vt7_15",
      dataKey: "damperOpeningData.vt7_15",
      label: "⑮ 2室給氣(左) (%)",
      order: 715,
    },
    {
      id: "damper_vt7_16",
      dataKey: "damperOpeningData.vt7_16",
      label: "⑯ 上部AC給氣(主) (%)",
      order: 716,
    },
    {
      id: "damper_vt7_17",
      dataKey: "damperOpeningData.vt7_17",
      label: "⑰ 下部AC給氣 (%)",
      order: 717,
    },
    {
      id: "damper_vt7_18",
      dataKey: "damperOpeningData.vt7_18",
      label: "⑱ 下部AC排氣 (%)",
      order: 718,
    },
    {
      id: "damper_vt7_19",
      dataKey: "damperOpeningData.vt7_19",
      label: "⑲ 1室排氣(左) (%)",
      order: 719,
    },
    {
      id: "damper_vt7_20",
      dataKey: "damperOpeningData.vt7_20",
      label: "⑳ 1室排氣(右) (%)",
      order: 720,
    },
    {
      id: "damper_vt7_21",
      dataKey: "damperOpeningData.vt7_21",
      label: "㉑ 1下部AC給氣(左) (%)",
      order: 721,
    },
    {
      id: "damper_vt7_22",
      dataKey: "damperOpeningData.vt7_22",
      label: "㉒ 1下部AC給氣(右) (%)",
      order: 722,
    },
    {
      id: "damper_vt7_23",
      dataKey: "damperOpeningData.vt7_23",
      label: "㉓ 2室排氣(左) (%)",
      order: 723,
    },
    {
      id: "damper_vt7_24",
      dataKey: "damperOpeningData.vt7_24",
      label: "㉔ 2室排氣(右) (%)",
      order: 724,
    },
    {
      id: "damper_vt7_25",
      dataKey: "damperOpeningData.vt7_25",
      label: "㉕ 2下部AC排氣(右) (%)",
      order: 725,
    },
    {
      id: "damper_vt7_26",
      dataKey: "damperOpeningData.vt7_26",
      label: "㉖ 2下部AC排氣(左) (%)",
      order: 726,
    },
    {
      id: "damper_vt7_27",
      dataKey: "damperOpeningData.vt7_27",
      label: "㉗ 2下部AC給氣(左) (%)",
      order: 727,
    },
    {
      id: "damper_vt7_28",
      dataKey: "damperOpeningData.vt7_28",
      label: "㉘ 2下部AC給氣(右) (%)",
      order: 728,
    },
    {
      id: "damper_vt7_29",
      dataKey: "damperOpeningData.vt7_29",
      label: "㉙ 下AC給氣(1室側) (%)",
      order: 729,
    },
    {
      id: "damper_vt7_30",
      dataKey: "damperOpeningData.vt7_30",
      label: "㉚ 下AC給氣(2室側) (%)",
      order: 730,
    },
    {
      id: "damper_vt7_31",
      dataKey: "damperOpeningData.vt7_31",
      label: "㉛ 1室外部新鮮空氣 (%)",
      order: 731,
    },
    {
      id: "damper_vt7_32",
      dataKey: "damperOpeningData.vt7_32",
      label: "㉜ 2室外部新鮮空氣 (%)",
      order: 732,
    },
    {
      id: "damper_vt7_34",
      dataKey: "damperOpeningData.vt7_34",
      label: "㉞ 1室給氣HEPA (%)",
      order: 734,
    },
    {
      id: "damper_vt7_35",
      dataKey: "damperOpeningData.vt7_35",
      label: "㉟ 2室給氣HEPA (%)",
      order: 735,
    },
  ]),

  vt6: createDamperConfig([
    {
      id: "damper_vt6_01",
      dataKey: "damperOpeningData.vt6_01",
      label: "① 上部AC排氣FAN (%)",
      order: 901,
    },
    {
      id: "damper_vt6_02",
      dataKey: "damperOpeningData.vt6_02",
      label: "② TOP室排氣(右) (%)",
      order: 902,
    },
    {
      id: "damper_vt6_03",
      dataKey: "damperOpeningData.vt6_03",
      label: "③ TOP室排氣(左) (%)",
      order: 903,
    },
    {
      id: "damper_vt6_04",
      dataKey: "damperOpeningData.vt6_04",
      label: "④ 1室上AC給氣(上) (%)",
      order: 904,
    },
    {
      id: "damper_vt6_05",
      dataKey: "damperOpeningData.vt6_05",
      label: "⑤ 1室上AC給氣(下) (%)",
      order: 905,
    },
    {
      id: "damper_vt6_06",
      dataKey: "damperOpeningData.vt6_06",
      label: "⑥ 1室上AC排氣(上右) (%)",
      order: 906,
    },
    {
      id: "damper_vt6_07",
      dataKey: "damperOpeningData.vt6_07",
      label: "⑦ 1室上AC排氣(上左) (%)",
      order: 907,
    },
    {
      id: "damper_vt6_08",
      dataKey: "damperOpeningData.vt6_08",
      label: "⑧ 1室上AC排氣(中右) (%)",
      order: 908,
    },
    {
      id: "damper_vt6_09",
      dataKey: "damperOpeningData.vt6_09",
      label: "⑨ 1室上AC排氣(中左) (%)",
      order: 909,
    },
    {
      id: "damper_vt6_10",
      dataKey: "damperOpeningData.vt6_10",
      label: "⑩ 1室上AC排氣(下右) (%)",
      order: 910,
    },
    {
      id: "damper_vt6_11",
      dataKey: "damperOpeningData.vt6_11",
      label: "⑪ 1室上AC排氣(下左) (%)",
      order: 911,
    },
    {
      id: "damper_vt6_12",
      dataKey: "damperOpeningData.vt6_12",
      label: "⑫ 1室給氣(右) (%)",
      order: 912,
    },
    {
      id: "damper_vt6_13",
      dataKey: "damperOpeningData.vt6_13",
      label: "⑬ 1室給氣(左) (%)",
      order: 913,
    },
    {
      id: "damper_vt6_14",
      dataKey: "damperOpeningData.vt6_14",
      label: "⑭ 2室上AC給氣 (%)",
      order: 914,
    },
    {
      id: "damper_vt6_15",
      dataKey: "damperOpeningData.vt6_15",
      label: "⑮ 2室上AC排氣(右) (%)",
      order: 915,
    },
    {
      id: "damper_vt6_16",
      dataKey: "damperOpeningData.vt6_16",
      label: "⑯ 2室上AC排氣(左) (%)",
      order: 916,
    },
    {
      id: "damper_vt6_17",
      dataKey: "damperOpeningData.vt6_17",
      label: "⑰ 2室給氣(右) (%)",
      order: 917,
    },
    {
      id: "damper_vt6_18",
      dataKey: "damperOpeningData.vt6_18",
      label: "⑱ 2室給氣(左) (%)",
      order: 918,
    },
    {
      id: "damper_vt6_19",
      dataKey: "damperOpeningData.vt6_19",
      label: "⑲ 上部AC給氣(主) (%)",
      order: 919,
    },
    {
      id: "damper_vt6_20",
      dataKey: "damperOpeningData.vt6_20",
      label: "⑳ 1室外部新鮮空氣 (%)",
      order: 920,
    },
    {
      id: "damper_vt6_21",
      dataKey: "damperOpeningData.vt6_21",
      label: "㉑ 2室外部新鮮空氣 (%)",
      order: 921,
    },
    {
      id: "damper_vt6_22",
      dataKey: "damperOpeningData.vt6_22",
      label: "㉒ 下部AC給氣 (%)",
      order: 922,
    },
    {
      id: "damper_vt6_23",
      dataKey: "damperOpeningData.vt6_23",
      label: "㉓ 下部AC排氣 (%)",
      order: 923,
    },
    {
      id: "damper_vt6_24",
      dataKey: "damperOpeningData.vt6_24",
      label: "㉔ 1室排氣(右) (%)",
      order: 924,
    },
    {
      id: "damper_vt6_25",
      dataKey: "damperOpeningData.vt6_25",
      label: "㉕ 1室排氣(左) (%)",
      order: 925,
    },
    {
      id: "damper_vt6_26",
      dataKey: "damperOpeningData.vt6_26",
      label: "㉖ 1下部AC給氣(右) (%)",
      order: 926,
    },
    {
      id: "damper_vt6_27",
      dataKey: "damperOpeningData.vt6_27",
      label: "㉗ 1下部AC給氣(左) (%)",
      order: 927,
    },
    {
      id: "damper_vt6_28",
      dataKey: "damperOpeningData.vt6_28",
      label: "㉘ 1下部AC給氣(副) (%)",
      order: 928,
    },
    {
      id: "damper_vt6_29",
      dataKey: "damperOpeningData.vt6_29",
      label: "㉙ 2室排氣(右) (%)",
      order: 929,
    },
    {
      id: "damper_vt6_30",
      dataKey: "damperOpeningData.vt6_30",
      label: "㉚ 2室排氣(左) (%)",
      order: 930,
    },
    {
      id: "damper_vt6_31",
      dataKey: "damperOpeningData.vt6_31",
      label: "㉛ 2下部AC排氣(右) (%)",
      order: 931,
    },
    {
      id: "damper_vt6_32",
      dataKey: "damperOpeningData.vt6_32",
      label: "㉜ 2下部AC排氣(左) (%)",
      order: 932,
    },
    {
      id: "damper_vt6_33",
      dataKey: "damperOpeningData.vt6_33",
      label: "㉝ 2下部AC給氣(右) (%)",
      order: 933,
    },
    {
      id: "damper_vt6_34",
      dataKey: "damperOpeningData.vt6_34",
      label: "㉞ 2下部AC給氣(左) (%)",
      order: 934,
    },
    {
      id: "damper_vt6_35",
      dataKey: "damperOpeningData.vt6_35",
      label: "㉟ 1室給氣HEPA (%)",
      order: 935,
    },
    {
      id: "damper_vt6_36",
      dataKey: "damperOpeningData.vt6_36",
      label: "㊱ 2室給氣HEPA (%)",
      order: 936,
    },
    {
      id: "damper_vt6_37",
      dataKey: "damperOpeningData.vt6_37",
      label: "㊲ 2下部AC給氣(副) (%)",
      order: 937,
    },
    {
      id: "damper_vt6_38",
      dataKey: "damperOpeningData.vt6_38",
      label: "㊳ 1室排氣風管(主) (%)",
      order: 938,
    },
    {
      id: "damper_vt6_39",
      dataKey: "damperOpeningData.vt6_39",
      label: "㊴ 2室排氣風管(主) (%)",
      order: 939,
    },
  ]),

  vt5: createDamperConfig([
    {
      id: "damper_vt5_01",
      dataKey: "damperOpeningData.vt5_01",
      label: "① TOP排氣扇(FAN) (%)",
      order: 801,
    },
    {
      id: "damper_vt5_02",
      dataKey: "damperOpeningData.vt5_02",
      label: "② TOP室排氣(右) (%)",
      order: 802,
    },
    {
      id: "damper_vt5_03",
      dataKey: "damperOpeningData.vt5_03",
      label: "③ TOP室排氣(左) (%)",
      order: 803,
    },
    {
      id: "damper_vt5_04",
      dataKey: "damperOpeningData.vt5_04",
      label: "④ 上部AC給氣(主) (%)",
      order: 804,
    },
    {
      id: "damper_vt5_05",
      dataKey: "damperOpeningData.vt5_05",
      label: "⑤ 1室上AC給氣(C) (%)",
      order: 805,
    },
    {
      id: "damper_vt5_06",
      dataKey: "damperOpeningData.vt5_06",
      label: "⑥ 1室上AC給氣(右) (%)",
      order: 806,
    },
    {
      id: "damper_vt5_07",
      dataKey: "damperOpeningData.vt5_07",
      label: "⑦ 1室上AC給氣(左) (%)",
      order: 807,
    },
    {
      id: "damper_vt5_08",
      dataKey: "damperOpeningData.vt5_08",
      label: "⑧ 1室上AC排氣(A) (%)",
      order: 808,
    },
    {
      id: "damper_vt5_09",
      dataKey: "damperOpeningData.vt5_09",
      label: "⑨ 1室上AC排氣(右) (%)",
      order: 809,
    },
    {
      id: "damper_vt5_10",
      dataKey: "damperOpeningData.vt5_10",
      label: "⑩ 1室上AC排氣(左) (%)",
      order: 810,
    },
    {
      id: "damper_vt5_11",
      dataKey: "damperOpeningData.vt5_11",
      label: "⑪ 1室給氣(右) (%)",
      order: 811,
    },
    {
      id: "damper_vt5_12",
      dataKey: "damperOpeningData.vt5_12",
      label: "⑫ 1室給氣(左) (%)",
      order: 812,
    },
    {
      id: "damper_vt5_13",
      dataKey: "damperOpeningData.vt5_13",
      label: "⑬ 2室上AC給氣(D) (%)",
      order: 813,
    },
    {
      id: "damper_vt5_14",
      dataKey: "damperOpeningData.vt5_14",
      label: "⑭ 2室上AC給氣(右) (%)",
      order: 814,
    },
    {
      id: "damper_vt5_15",
      dataKey: "damperOpeningData.vt5_15",
      label: "⑮ 2室上AC給氣(左) (%)",
      order: 815,
    },
    {
      id: "damper_vt5_16",
      dataKey: "damperOpeningData.vt5_16",
      label: "⑯ 2室上AC排氣(B) (%)",
      order: 816,
    },
    {
      id: "damper_vt5_17",
      dataKey: "damperOpeningData.vt5_17",
      label: "⑰ 2室上AC排氣(右) (%)",
      order: 817,
    },
    {
      id: "damper_vt5_18",
      dataKey: "damperOpeningData.vt5_18",
      label: "⑱ 2室上AC排氣(左) (%)",
      order: 818,
    },
    {
      id: "damper_vt5_19",
      dataKey: "damperOpeningData.vt5_19",
      label: "⑲ 2室給氣(右) (%)",
      order: 819,
    },
    {
      id: "damper_vt5_20",
      dataKey: "damperOpeningData.vt5_20",
      label: "⑳ 2室給氣(左) (%)",
      order: 820,
    },
    {
      id: "damper_vt5_21",
      dataKey: "damperOpeningData.vt5_21",
      label: "㉑ 1室外部新鮮空氣 (%)",
      order: 821,
    },
    {
      id: "damper_vt5_22",
      dataKey: "damperOpeningData.vt5_22",
      label: "㉒ 2室外部新鮮空氣 (%)",
      order: 822,
    },
    {
      id: "damper_vt5_23",
      dataKey: "damperOpeningData.vt5_23",
      label: "㉓ 下部AC給氣(主) (%)",
      order: 823,
    },
    {
      id: "damper_vt5_24",
      dataKey: "damperOpeningData.vt5_24",
      label: "㉔ 下部AC排氣FAN (%)",
      order: 824,
    },
    {
      id: "damper_vt5_25",
      dataKey: "damperOpeningData.vt5_25",
      label: "㉕ 1室排氣(右) (%)",
      order: 825,
    },
    {
      id: "damper_vt5_26",
      dataKey: "damperOpeningData.vt5_26",
      label: "㉖ 1室排氣(左) (%)",
      order: 826,
    },
    {
      id: "damper_vt5_27",
      dataKey: "damperOpeningData.vt5_27",
      label: "㉗ 1下部AC排氣(右) (%)",
      order: 827,
    },
    {
      id: "damper_vt5_28",
      dataKey: "damperOpeningData.vt5_28",
      label: "㉘ 1下部AC排氣(左) (%)",
      order: 828,
    },
    {
      id: "damper_vt5_29",
      dataKey: "damperOpeningData.vt5_29",
      label: "㉙ 1下部AC給氣(右) (%)",
      order: 829,
    },
    {
      id: "damper_vt5_30",
      dataKey: "damperOpeningData.vt5_30",
      label: "㉚ 1下部AC給氣(左) (%)",
      order: 830,
    },
    {
      id: "damper_vt5_31",
      dataKey: "damperOpeningData.vt5_31",
      label: "㉛ 2室排氣(右) (%)",
      order: 831,
    },
    {
      id: "damper_vt5_32",
      dataKey: "damperOpeningData.vt5_32",
      label: "㉜ 2室排氣(左) (%)",
      order: 832,
    },
    {
      id: "damper_vt5_33",
      dataKey: "damperOpeningData.vt5_33",
      label: "㉝ 2下部AC排氣(右) (%)",
      order: 833,
    },
    {
      id: "damper_vt5_34",
      dataKey: "damperOpeningData.vt5_34",
      label: "㉞ 2下部AC排氣(左) (%)",
      order: 834,
    },
    {
      id: "damper_vt5_35",
      dataKey: "damperOpeningData.vt5_35",
      label: "㉟ 2下部AC給氣(右) (%)",
      order: 835,
    },
    {
      id: "damper_vt5_36",
      dataKey: "damperOpeningData.vt5_36",
      label: "㊱ 2下部AC給氣(左) (%)",
      order: 836,
    },
    {
      id: "damper_vt5_37",
      dataKey: "damperOpeningData.vt5_37",
      label: "㊲ 1室下AC給氣(副) (%)",
      order: 837,
    },
    {
      id: "damper_vt5_38",
      dataKey: "damperOpeningData.vt5_38",
      label: "㊳ 2室下AC給氣(副) (%)",
      order: 838,
    },
  ]),
  vt1: createDamperConfig([
    {
      id: "damper_vt1_01",
      dataKey: "damperOpeningData.vt1_01",
      label: "① TOP室排氣(右) (%)",
      order: 1001,
    },
    {
      id: "damper_vt1_02",
      dataKey: "damperOpeningData.vt1_02",
      label: "② TOP室排氣(左) (%)",
      order: 1002,
    },
    {
      id: "damper_vt1_03",
      dataKey: "damperOpeningData.vt1_03",
      label: "③ 1室上AC給氣(右) (%)",
      order: 1003,
    },
    {
      id: "damper_vt1_04",
      dataKey: "damperOpeningData.vt1_04",
      label: "④ 1室上AC給氣(左) (%)",
      order: 1004,
    },
    {
      id: "damper_vt1_05",
      dataKey: "damperOpeningData.vt1_05",
      label: "⑤ 1室上AC排氣(右) (%)",
      order: 1005,
    },
    {
      id: "damper_vt1_06",
      dataKey: "damperOpeningData.vt1_06",
      label: "⑥ 1室上AC排氣(左) (%)",
      order: 1006,
    },
    {
      id: "damper_vt1_07",
      dataKey: "damperOpeningData.vt1_07",
      label: "⑦ 1室給氣(右) (%)",
      order: 1007,
    },
    {
      id: "damper_vt1_08",
      dataKey: "damperOpeningData.vt1_08",
      label: "⑧ 1室給氣(左) (%)",
      order: 1008,
    },
    {
      id: "damper_vt1_09",
      dataKey: "damperOpeningData.vt1_09",
      label: "⑨ 2室上AC給氣(右) (%)",
      order: 1009,
    },
    {
      id: "damper_vt1_10",
      dataKey: "damperOpeningData.vt1_10",
      label: "⑩ 2室上AC給氣(左) (%)",
      order: 1010,
    },
    {
      id: "damper_vt1_11",
      dataKey: "damperOpeningData.vt1_11",
      label: "⑪ 2室上AC排氣(右) (%)",
      order: 1011,
    },
    {
      id: "damper_vt1_12",
      dataKey: "damperOpeningData.vt1_12",
      label: "⑫ 2室上AC排氣(左) (%)",
      order: 1012,
    },
    {
      id: "damper_vt1_13",
      dataKey: "damperOpeningData.vt1_13",
      label: "⑬ 2室給氣(右) (%)",
      order: 1013,
    },
    {
      id: "damper_vt1_14",
      dataKey: "damperOpeningData.vt1_14",
      label: "⑭ 2室給氣(左) (%)",
      order: 1014,
    },
    {
      id: "damper_vt1_15",
      dataKey: "damperOpeningData.vt1_15",
      label: "⑮ 1室外部新鮮空氣 (%)",
      order: 1015,
    },
    {
      id: "damper_vt1_16",
      dataKey: "damperOpeningData.vt1_16",
      label: "⑯ 1室給氣(含浸室) (%)",
      order: 1016,
    },
    {
      id: "damper_vt1_17",
      dataKey: "damperOpeningData.vt1_17",
      label: "⑰ 2室外部新鮮空氣 (%)",
      order: 1017,
    },
    {
      id: "damper_vt1_18",
      dataKey: "damperOpeningData.vt1_18",
      label: "⑱ 2室給氣(含浸室) (%)",
      order: 1018,
    },
    {
      id: "damper_vt1_19",
      dataKey: "damperOpeningData.vt1_19",
      label: "⑲ 下部AC進氣 (%)",
      order: 1019,
    },
    {
      id: "damper_vt1_20",
      dataKey: "damperOpeningData.vt1_20",
      label: "⑳ 下部AC給氣 (%)",
      order: 1020,
    },
    {
      id: "damper_vt1_21",
      dataKey: "damperOpeningData.vt1_21",
      label: "㉑ 下部AC排氣 (%)",
      order: 1021,
    },
    {
      id: "damper_vt1_22",
      dataKey: "damperOpeningData.vt1_22",
      label: "㉒ 1室排氣(右) (%)",
      order: 1022,
    },
    {
      id: "damper_vt1_23",
      dataKey: "damperOpeningData.vt1_23",
      label: "㉓ 1室排氣(左) (%)",
      order: 1023,
    },
    {
      id: "damper_vt1_24",
      dataKey: "damperOpeningData.vt1_24",
      label: "㉔ 1下部AC排氣(右) (%)",
      order: 1024,
    },
    {
      id: "damper_vt1_25",
      dataKey: "damperOpeningData.vt1_25",
      label: "㉕ 1下部AC排氣(左) (%)",
      order: 1025,
    },
    {
      id: "damper_vt1_26",
      dataKey: "damperOpeningData.vt1_26",
      label: "㉖ 1下部AC給氣(右) (%)",
      order: 1026,
    },
    {
      id: "damper_vt1_27",
      dataKey: "damperOpeningData.vt1_27",
      label: "㉗ 1下部AC給氣(左) (%)",
      order: 1027,
    },
    {
      id: "damper_vt1_28",
      dataKey: "damperOpeningData.vt1_28",
      label: "㉘ 2室排氣(右) (%)",
      order: 1028,
    },
    {
      id: "damper_vt1_29",
      dataKey: "damperOpeningData.vt1_29",
      label: "㉙ 2室排氣(左) (%)",
      order: 1029,
    },
    {
      id: "damper_vt1_30",
      dataKey: "damperOpeningData.vt1_30",
      label: "㉚ 2下部AC排氣(右) (%)",
      order: 1030,
    },
    {
      id: "damper_vt1_31",
      dataKey: "damperOpeningData.vt1_31",
      label: "㉛ 2下部AC排氣(左) (%)",
      order: 1031,
    },
    {
      id: "damper_vt1_32",
      dataKey: "damperOpeningData.vt1_32",
      label: "㉜ 2下部AC給氣(右) (%)",
      order: 1032,
    },
    {
      id: "damper_vt1_33",
      dataKey: "damperOpeningData.vt1_33",
      label: "㉝ 2下部AC給氣(左) (%)",
      order: 1033,
    },
    {
      id: "damper_vt1_34",
      dataKey: "damperOpeningData.vt1_34",
      label: "㉞ 含浸室排氣(右) (%)",
      order: 1034,
    },
    {
      id: "damper_vt1_35",
      dataKey: "damperOpeningData.vt1_35",
      label: "㉟ 含浸室排氣(左) (%)",
      order: 1035,
    },
    {
      id: "damper_vt1_36",
      dataKey: "damperOpeningData.vt1_36",
      label: "㊱ 含浸室新鮮給氣 (%)",
      order: 1036,
    },
    {
      id: "damper_vt1_37",
      dataKey: "damperOpeningData.vt1_37",
      label: "㊲ 1室給氣HEPA (%)",
      order: 1037,
    },
    {
      id: "damper_vt1_38",
      dataKey: "damperOpeningData.vt1_38",
      label: "㊳ 2室給氣HEPA (%)",
      order: 1038,
    },
    {
      id: "damper_vt1_39",
      dataKey: "damperOpeningData.vt1_39",
      label: "㊴ 上部AC給氣HEPA (%)",
      order: 1039,
    },
    {
      id: "damper_vt1_40",
      dataKey: "damperOpeningData.vt1_40",
      label: "㊵ 下部AC給氣HEPA (%)",
      order: 1040,
    },
    {
      id: "damper_vt1_41",
      dataKey: "damperOpeningData.vt1_41",
      label: "㊶ 上部AC給氣(主) (%)",
      order: 1041,
    },
  ]),
};

// -------------------------------------------------------------------
// 機外顯示與風量設定 (評價TEAM用) - 動態配置
// -------------------------------------------------------------------
const getAirAndExternalFieldsByModel = (model) => {
  const commonFields = [
    {
      id: "airExternal_chamber1_supply_hz_rpm",
      dataKey: "airExternal_chamber1_supply_hz_rpm",
      label: "一室給氣 (Hz/RPM)",
      csvHeader: "風量設定&機外顯示_一室給氣 (Hz/RPM)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 32,
      inTable: true,
    },
    {
      id: "airExternal_chamber1_exhaust_hz_rpm",
      dataKey: "airExternal_chamber1_exhaust_hz_rpm",
      label: "一室排氣 (Hz/RPM)",
      csvHeader: "風量設定&機外顯示_一室排氣 (Hz/RPM)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 33,
      inTable: true,
    },
    {
      id: "airExternal_chamber2_supply_hz_rpm",
      dataKey: "airExternal_chamber2_supply_hz_rpm",
      label: "二室給氣 (Hz/RPM)",
      csvHeader: "風量設定&機外顯示_二室給氣 (Hz/RPM)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 34,
      inTable: true,
    },
    {
      id: "airExternal_chamber2_exhaust_hz_rpm",
      dataKey: "airExternal_chamber2_exhaust_hz_rpm",
      label: "二室排氣 (Hz/RPM)",
      csvHeader: "風量設定&機外顯示_二室排氣 (Hz/RPM)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 35,
      inTable: true,
    },
    {
      id: "airExternal_top_roll_chamber_celsius",
      dataKey: "airExternal_top_roll_chamber_celsius",
      label: "Top ROLL室 (℃)",
      csvHeader: "風量設定&機外顯示_Top ROLL室 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 36,
      inTable: true,
    },
    {
      id: "airExternal_top_exhaust_hz",
      dataKey: "airExternal_top_exhaust_hz",
      label: "Top排 (Hz)",
      csvHeader: "風量設定&機外顯示_Top排 (Hz)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 37,
      inTable: true,
    },
    {
      id: "airExternal_ac_hz",
      dataKey: "airExternal_ac_hz",
      label: "AC (Hz)",
      csvHeader: "風量設定&機外顯示_AC (Hz)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 38,
      inTable: true,
    },
    {
      id: "airExternal_impregnation_chamber_celsius",
      dataKey: "airExternal_impregnation_chamber_celsius",
      label: "含浸室 (℃)",
      csvHeader: "風量設定&機外顯示_含浸室 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 39,
      inTable: true,
    },
  ];

  const modelSpecificFields = [];

  if (model === "vt6") {
    modelSpecificFields.push({
      id: "airExternal_upper_ac_exhaust_hz",
      dataKey: "airExternal_upper_ac_exhaust_hz",
      label: "上AC排 (Hz)",
      csvHeader: "風量設定&機外顯示_上AC排 (Hz)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 38.1,
      inTable: true,
    });
  } else if (model === "vt7") {
    modelSpecificFields.push({
      id: "airExternal_built_in_ac_hz",
      dataKey: "airExternal_built_in_ac_hz",
      label: "內建AC (Hz)",
      csvHeader: "風量設定&機外顯示_內建AC (Hz)",
      recordTypes: ["evaluationTeam"],
      group: "airExternal",
      elemType: "number",
      parentId: "evaluationTeam_airAndExternal_grid",
      order: 38.2,
      inTable: true,
    });
  }

  const combinedFields = [...commonFields, ...modelSpecificFields];
  combinedFields.sort((a, b) => a.order - b.order);

  return combinedFields;
};

// -------------------------------------------------------------------
// ▼▼▼ 主要的欄位設定生成函式 (現在是唯一的核心函式) ▼▼▼
// -------------------------------------------------------------------
const generateFieldConfigurations = (currentDryerModel = "vt8") => {
  // 1. 基本資訊 (所有模式通用)
  const baseFields = [
    {
      id: "recordTypeDisplay",
      dataKey: "recordType",
      isHeader: true,
      label: "類型",
      csvHeader: "類型",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "display",
      order: 1,
      inTable: true,
    },
    {
      id: "dryerModelDisplay",
      dataKey: "dryerModel",
      isHeader: true,
      label: "機台型號",
      csvHeader: "機台型號",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "display",
      order: 2,
      inTable: true,
    },
    {
      id: "rtoStatus",
      dataKey: "rtoStatus",
      label: "RTO啟用狀態",
      csvHeader: "RTO啟用狀態",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "radio", // 我們定義一個新的類型 'radio'
      order: 2.5, // 讓它排在機型後面
      inTable: true,
    },
    // ▼▼▼ 新增開始 ▼▼▼
    {
      id: "heatingStatus",
      dataKey: "heatingStatus",
      label: "升溫啟用狀態",
      csvHeader: "升溫狀態",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "radio",
      order: 2.6, // 讓它排在RTO後面
      inTable: true,
    },
    // ▲▲▲ 新增結束 ▲▲▲
    {
      id: "dateTime",
      dataKey: "dateTime",
      isHeader: true,
      label: "記錄日期時間",
      csvHeader: "日期時間",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "datetime-local",
      required: true,
      order: 3,
      inTable: true,
    },
    {
      id: "remark",
      dataKey: "remark",
      isHeader: true,
      label: "備註",
      csvHeader: "備註",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "basic",
      elemType: "textarea",
      order: 4,
      inTable: true,
    },
  ];

  // 2. 評價 TEAM 專用欄位
  const recorder1Fields = [
    {
      id: "recorder1_chamber1_lower",
      dataKey: "recorder1Data.chamber1_lower",
      label: "實測第一紀錄器_1室下 (℃)",
      csvHeader: "實測第一紀錄器_1室下 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 11,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_upper",
      dataKey: "recorder1Data.chamber1_upper",
      label: "實測第一紀錄器_1室上 (℃)",
      csvHeader: "實測第一紀錄器_1室上 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 12,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_supply",
      dataKey: "recorder1Data.chamber1_supply",
      label: "實測第一紀錄器_1室給氣 (℃)",
      csvHeader: "實測第一紀錄器_1室給氣 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 13,
      inTable: true,
    },
    {
      id: "recorder1_chamber2_supply",
      dataKey: "recorder1Data.chamber2_supply",
      label: "實測第一紀錄器_2室給氣 (℃)",
      csvHeader: "實測第一紀錄器_2室給氣 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 14,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_lower_right",
      dataKey: "recorder1Data.chamber1_lower_right",
      label: "實測第一紀錄器_1下右 (℃)",
      csvHeader: "實測第一紀錄器_1下右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 15,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_lower_middle",
      dataKey: "recorder1Data.chamber1_lower_middle",
      label: "實測第一紀錄器_1下中 (℃)",
      csvHeader: "實測第一紀錄器_1下中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 16,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_lower_left",
      dataKey: "recorder1Data.chamber1_lower_left",
      label: "實測第一紀錄器_1下左 (℃)",
      csvHeader: "實測第一紀錄器_1下左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 17,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_middle_middle",
      dataKey: "recorder1Data.chamber1_middle_middle",
      label: "實測第一紀錄器_1中中 (℃)",
      csvHeader: "實測第一紀錄器_1中中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 18,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_upper_right",
      dataKey: "recorder1Data.chamber1_upper_right",
      label: "實測第一紀錄器_1上右 (℃)",
      csvHeader: "實測第一紀錄器_1上右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 19,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_upper_middle",
      dataKey: "recorder1Data.chamber1_upper_middle",
      label: "實測第一紀錄器_1上中 (℃)",
      csvHeader: "實測第一紀錄器_1上中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 20,
      inTable: true,
    },
    {
      id: "recorder1_chamber1_upper_left",
      dataKey: "recorder1Data.chamber1_upper_left",
      label: "實測第一紀錄器_1上左 (℃)",
      csvHeader: "實測第一紀錄器_1上左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder1",
      elemType: "number",
      parentId: "evaluationTeam_recorder1_grid",
      order: 21,
      inTable: true,
    },
  ];
  const recorder2Fields = [
    {
      id: "recorder2_chamber2_upper_right",
      dataKey: "recorder2Data.chamber2_upper_right",
      label: "實測第二紀錄器_2上右 (℃)",
      csvHeader: "實測第二紀錄器_2上右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 22,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_upper_middle",
      dataKey: "recorder2Data.chamber2_upper_middle",
      label: "實測第二紀錄器_2上中 (℃)",
      csvHeader: "實測第二紀錄器_2上中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 23,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_upper_left",
      dataKey: "recorder2Data.chamber2_upper_left",
      label: "實測第二紀錄器_2上左 (℃)",
      csvHeader: "實測第二紀錄器_2上左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 24,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_room_right",
      dataKey: "recorder2Data.chamber2_room_right",
      label: "實測第二紀錄器_2室右 (℃)",
      csvHeader: "實測第二紀錄器_2室右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 25,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_room_middle",
      dataKey: "recorder2Data.chamber2_room_middle",
      label: "實測第二紀錄器_2室中 (℃)",
      csvHeader: "實測第二紀錄器_2室中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 26,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_room_left",
      dataKey: "recorder2Data.chamber2_room_left",
      label: "實測第二紀錄器_2室左 (℃)",
      csvHeader: "實測第二紀錄器_2室左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 27,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_middle_middle",
      dataKey: "recorder2Data.chamber2_middle_middle",
      label: "實測第二紀錄器_2中中 (℃)",
      csvHeader: "實測第二紀錄器_2中中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 28,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_lower_right",
      dataKey: "recorder2Data.chamber2_lower_right",
      label: "實測第二紀錄器_2下右 (℃)",
      csvHeader: "實測第二紀錄器_2下右 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 29,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_lower_middle",
      dataKey: "recorder2Data.chamber2_lower_middle",
      label: "實測第二紀錄器_2下中 (℃)",
      csvHeader: "實測第二紀錄器_2下中 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 30,
      inTable: true,
    },
    {
      id: "recorder2_chamber2_lower_left",
      dataKey: "recorder2Data.chamber2_lower_left",
      label: "實測第二紀錄器_2下左 (℃)",
      csvHeader: "實測第二紀錄器_2下左 (℃)",
      recordTypes: ["evaluationTeam"],
      group: "recorder2",
      elemType: "number",
      parentId: "evaluationTeam_recorder2_grid",
      order: 31,
      inTable: true,
    },
  ];

  const airAndExternalFields =
    getAirAndExternalFieldsByModel(currentDryerModel);

  const airVolumeGeneratedFields = [];
  getAirVolumeMeasurementsByModel(currentDryerModel).forEach((measure) => {
    // ★★★★★ 修正開始 ★★★★★
    // 建立一個獨一無二的 CSV 標頭前綴
    const csvHeaderPrefix = `${currentDryerModel.toUpperCase()}_${
      measure.label
    }`;
    // ★★★★★ 修正結束 ★★★★★

    if (measure.status === "normal") {
      airVolumeGeneratedFields.push(
        {
          id: `air_speed_${measure.id}`,
          dataKey: `airVolumes.${measure.id}.speed`,
          label: `${measure.label}_風速(m/s)`,
          // 使用新的、獨一無二的標頭
          csvHeader: `${csvHeaderPrefix}_風速(m/s)`,
          recordTypes: ["evaluationTeam"],
          group: "airVolumeInput",
          elemType: "number",
          isDynamicInput: true,
          parentId: "airVolumeGrid",
          order: measure.order + 0.1,
          inTable: true,
        },
        {
          id: `air_temp_${measure.id}`,
          dataKey: `airVolumes.${measure.id}.temp`,
          label: `${measure.label}_溫度(℃)`,
          // 使用新的、獨一無二的標頭
          csvHeader: `${csvHeaderPrefix}_溫度(℃)`,
          recordTypes: ["evaluationTeam"],
          group: "airVolumeInput",
          elemType: "number",
          isDynamicInput: true,
          parentId: "airVolumeGrid",
          order: measure.order + 0.2,
          inTable: true,
        },
        {
          id: `air_volume_${measure.id}`,
          dataKey: `airVolumes.${measure.id}.volume`,
          label: `${measure.label}_風量(Nm³/分)`,
          // 使用新的、獨一無二的標頭
          csvHeader: `${csvHeaderPrefix}_風量(Nm³/分)`,
          recordTypes: ["evaluationTeam"],
          group: "airVolumeDisplay",
          elemType: "calculatedText",
          isCalculated: true,
          isDynamicInput: true,
          parentId: "airVolumeGrid",
          order: measure.order + 0.3,
          inTable: true,
        }
      );
    } else {
      airVolumeGeneratedFields.push({
        id: `air_status_${currentDryerModel}_${measure.id}`,
        dataKey: `airVolumes.${measure.id}.status`,
        label: `${measure.label}_狀態`,
        // 使用新的、獨一無二的標頭
        csvHeader: `${csvHeaderPrefix}_狀態`,
        recordTypes: ["evaluationTeam"],
        group: "airVolumeInput",
        elemType: "displayStatus",
        isDynamicInput: true,
        parentId: "airVolumeGrid",
        order: measure.order + 0.1,
        inTable: true,
        displayValue: measure.status,
      });
    }
  });

  const techTempGeneratedFields = [];
  techTempPoints.forEach((point) => {
    const recordPointKey = `point${
      point.id.startsWith("T") ? point.id : parseInt(point.id)
    }`;
    const baseLabel = point.label.replace("技術溫測實溫_", "");
    const baseOrder = point.orderOffset;
    for (let i = 1; i <= 5; i++) {
      techTempGeneratedFields.push({
        id: `techTemp_${point.id}_${i}`,
        dataKey: `actualTemps.${recordPointKey}.val${i}`,
        label: `${point.label}.${i}(℃)`,
        csvHeader: `${baseLabel}.${i}(℃)`,
        recordTypes: ["evaluationTeam"],
        group: "techTempInput",
        elemType: "number",
        isDynamicInput: true,
        parentId: "techTempGrid",
        order: baseOrder + i,
        inTable: true,
      });
    }
    techTempGeneratedFields.push({
      id: `techTemp_${point.id}_diff`,
      dataKey: `actualTemps.${recordPointKey}.diff`,
      label: `${point.label}.溫差(℃)`,
      csvHeader: `${baseLabel}.溫差(℃)`,
      recordTypes: ["evaluationTeam"],
      group: "techTempDisplay",
      elemType: "calculatedText",
      isCalculated: true,
      isDynamicInput: true,
      parentId: "techTempGrid",
      order: baseOrder + 6,
      inTable: false,
    });
  });

  // 3. 條件設定專用欄位 (靜態部分)
  const staticConditionSettingFields = [
    {
      id: "fan_setting_chamber1_supply",
      dataKey: "fan_setting_chamber1_supply",
      label: "FAN_１室給氣 (Hz/RPM)",
      csvHeader: "FAN_１室給氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 500,
      inTable: true,
    },
    {
      id: "fan_setting_chamber1_exhaust",
      dataKey: "fan_setting_chamber1_exhaust",
      label: "FAN_１室排氣 (Hz/RPM)",
      csvHeader: "FAN_１室排氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 501,
      inTable: true,
    },
    {
      id: "fan_setting_chamber2_supply",
      dataKey: "fan_setting_chamber2_supply",
      label: "FAN_２室給氣 (Hz/RPM)",
      csvHeader: "FAN_２室給氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 502,
      inTable: true,
    },
    {
      id: "fan_setting_chamber2_exhaust",
      dataKey: "fan_setting_chamber2_exhaust",
      label: "FAN_２室排氣 (Hz/RPM)",
      csvHeader: "FAN_２室排氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 503,
      inTable: true,
    },
    {
      id: "fan_setting_upper_ac_exhaust",
      dataKey: "fan_setting_upper_ac_exhaust",
      label: "FAN_上部AC排氣 (Hz/RPM)",
      csvHeader: "FAN_上部AC排氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 504,
      inTable: true,
    },
    {
      id: "fan_setting_upper_ac_supply",
      dataKey: "fan_setting_upper_ac_supply",
      label: "FAN_上部AC給氣 (Hz/RPM)",
      csvHeader: "FAN_上部AC給氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 505,
      inTable: true,
    },
    {
      id: "fan_setting_lower_ac_exhaust",
      dataKey: "fan_setting_lower_ac_exhaust",
      label: "FAN_下部AC排氣 (Hz/RPM)",
      csvHeader: "FAN_下部AC排氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 506,
      inTable: true,
    },
    {
      id: "fan_setting_lower_ac_supply",
      dataKey: "fan_setting_lower_ac_supply",
      label: "FAN_下部AC給氣 (Hz/RPM)",
      csvHeader: "FAN_下部AC給氣 (Hz/RPM)",
      recordTypes: ["conditionSetting"],
      group: "fanSetting",
      elemType: "number",
      order: 507,
      inTable: true,
    },
    {
      id: "set_temp_chamber1_supply",
      dataKey: "set_temp_chamber1_supply",
      label: "設定_１室給氣 (℃)",
      csvHeader: "設定_１室給氣 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5,
      inTable: true,
    },
    {
      id: "set_temp_chamber1_upper_heat",
      dataKey: "set_temp_chamber1_upper_heat",
      label: "設定_１室上部熱煤 (℃)",
      csvHeader: "設定_１室上部熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.1,
      inTable: true,
    },
    {
      id: "set_temp_chamber1_lower_heat",
      dataKey: "set_temp_chamber1_lower_heat",
      label: "設定_１室下部熱煤 (℃)",
      csvHeader: "設定_１室下部熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.2,
      inTable: true,
    },
    {
      id: "set_temp_chamber2_supply",
      dataKey: "set_temp_chamber2_supply",
      label: "設定_２室給氣 (℃)",
      csvHeader: "設定_２室給氣 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.3,
      inTable: true,
    },
    {
      id: "set_temp_chamber2_right_heat",
      dataKey: "set_temp_chamber2_right_heat",
      label: "設定_２室右熱煤 (℃)",
      csvHeader: "設定_２室右熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.4,
      inTable: true,
    },
    {
      id: "set_temp_chamber2_middle_heat",
      dataKey: "set_temp_chamber2_middle_heat",
      label: "設定_２室中熱煤 (℃)",
      csvHeader: "設定_２室中熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.5,
      inTable: true,
    },
    {
      id: "set_temp_chamber2_left_heat",
      dataKey: "set_temp_chamber2_left_heat",
      label: "設定_２室左熱煤 (℃)",
      csvHeader: "設定_２室左熱煤 (℃)",
      recordTypes: ["evaluationTeam", "conditionSetting"],
      group: "tempSetting",
      elemType: "number",
      order: 5.6,
      inTable: true,
    },
    {
      id: "dryer_chamber1_lower_left",
      dataKey: "dryer_chamber1_lower_left",
      label: "乾燥機內實溫_１室下 左 (°C)",
      csvHeader: "乾燥機內實溫_１室下 左 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 520,
      inTable: true,
    },
    {
      id: "dryer_chamber1_lower_middle",
      dataKey: "dryer_chamber1_lower_middle",
      label: "乾燥機內實溫_１室下 中 (°C)",
      csvHeader: "乾燥機內實溫_１室下 中 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 521,
      inTable: true,
    },
    {
      id: "dryer_chamber1_lower_right",
      dataKey: "dryer_chamber1_lower_right",
      label: "乾燥機內實溫_１室下 右 (°C)",
      csvHeader: "乾燥機內實溫_１室下 右 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 522,
      inTable: true,
    },
    {
      id: "dryer_chamber1_upper_left",
      dataKey: "dryer_chamber1_upper_left",
      label: "乾燥機內實溫_１室上 左 (°C)",
      csvHeader: "乾燥機內實溫_１室上 左 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 523,
      inTable: true,
    },
    {
      id: "dryer_chamber1_upper_middle",
      dataKey: "dryer_chamber1_upper_middle",
      label: "乾燥機內實溫_１室上 中 (°C)",
      csvHeader: "乾燥機內實溫_１室上 中 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 524,
      inTable: true,
    },
    {
      id: "dryer_chamber1_upper_right",
      dataKey: "dryer_chamber1_upper_right",
      label: "乾燥機內實溫_１室上 右 (°C)",
      csvHeader: "乾燥機內實溫_１室上 右 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 525,
      inTable: true,
    },
    {
      id: "dryer_chamber2_upper_left",
      dataKey: "dryer_chamber2_upper_left",
      label: "乾燥機內實溫_２室上 左 (°C)",
      csvHeader: "乾燥機內實溫_２室上 左 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 526,
      inTable: true,
    },
    {
      id: "dryer_chamber2_upper_middle",
      dataKey: "dryer_chamber2_upper_middle",
      label: "乾燥機內實溫_２室上 中 (°C)",
      csvHeader: "乾燥機內實溫_２室上 中 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 527,
      inTable: true,
    },
    {
      id: "dryer_chamber2_upper_right",
      dataKey: "dryer_chamber2_upper_right",
      label: "乾燥機內實溫_２室上 右 (°C)",
      csvHeader: "乾燥機內實溫_２室上 右 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 528,
      inTable: true,
    },
    {
      id: "dryer_chamber2_lower_left",
      dataKey: "dryer_chamber2_lower_left",
      label: "乾燥機內實溫_２室下 左 (°C)",
      csvHeader: "乾燥機內實溫_２室下 左 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 529,
      inTable: true,
    },
    {
      id: "dryer_chamber2_lower_middle",
      dataKey: "dryer_chamber2_lower_middle",
      label: "乾燥機內實溫_２室下 中 (°C)",
      csvHeader: "乾燥機內實溫_２室下 中 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 530,
      inTable: true,
    },
    {
      id: "dryer_chamber2_lower_right",
      dataKey: "dryer_chamber2_lower_right",
      label: "乾燥機內實溫_２室下 右 (°C)",
      csvHeader: "乾燥機內實溫_２室下 右 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 531,
      inTable: true,
    },
    {
      id: "dryer_top_roll_chamber",
      dataKey: "dryer_top_roll_chamber",
      label: "乾燥機內實溫_Top Roll室 (°C)",
      csvHeader: "乾燥機內實溫_Top Roll室 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 532,
      inTable: true,
    },
    {
      id: "dryer_impregnation_chamber",
      dataKey: "dryer_impregnation_chamber",
      label: "乾燥機內實溫_含浸室 (°C)",
      csvHeader: "乾燥機內實溫_含浸室 (°C)",
      recordTypes: ["conditionSetting"],
      group: "dryerTemp",
      elemType: "number",
      order: 533,
      inTable: true,
    },
  ];

  // 4. 條件設定專用欄位 (Damper, 動態)
  const damperFields = allDamperOpeningFields[currentDryerModel] || [];

  // 5. 條件設定專用欄位 (HMI, 動態)
  const hmiGeneratedFields = [];
  const modelHmiConfig = hmiFieldsByModel[currentDryerModel] || {};
  for (const sectionKey in modelHmiConfig) {
    const fieldsInSection = modelHmiConfig[sectionKey] || [];
    fieldsInSection.forEach((field) => {
      hmiGeneratedFields.push({
        id: field.id,
        dataKey: `hmiData.${sectionKey}.${field.id}`,
        label: field.label,
        csvHeader: `HMI_${field.label
          .replace(/<small>.*<\/small>/, "")
          .replace(/\d+\.\s*/, "")}`,
        recordTypes: ["conditionSetting"],
        group: sectionKey,
        elemType: "number",
        order: 700 + (parseInt(field.label) || 0),
        inTable: true,
        validation: field.validation,
        isHmiField: true,
        position: field.position,
      });
    });
  }

  // 6. 組合所有欄位
  const allFields = [
    ...baseFields,
    ...recorder1Fields,
    ...recorder2Fields,
    ...airAndExternalFields, // 使用動態生成的 airAndExternalFields
    ...airVolumeGeneratedFields,
    ...techTempGeneratedFields,
    ...staticConditionSettingFields,
    ...damperFields,
    ...hmiGeneratedFields,
  ];

  allFields.sort((a, b) => (a.order || Infinity) - (b.order || Infinity));
  return allFields;
};

// 匯出函式與變數，保持不變
export {
  LOCAL_STORAGE_KEY,
  techTempPoints,
  generateFieldConfigurations,
  getAirVolumeMeasurementsByModel,
  allDryerAirVolumeMeasurements,
  hmiLayouts,
  hmiFieldsByModel,
  allDamperOpeningFields,
  damperLayoutsByModel,
};
